// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projects.Models;

#nullable disable

namespace Projects.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20230923104137_re")]
    partial class re
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projects.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 9, 23, 13, 41, 37, 568, DateTimeKind.Local).AddTicks(1268),
                            Name = "Project 1",
                            Type = "Type 1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 9, 23, 13, 41, 37, 568, DateTimeKind.Local).AddTicks(1393),
                            Name = "Project 2",
                            Type = "Type 2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 9, 23, 13, 41, 37, 568, DateTimeKind.Local).AddTicks(1399),
                            Name = "Project 3",
                            Type = "Type 3"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 9, 23, 13, 41, 37, 568, DateTimeKind.Local).AddTicks(1403),
                            Name = "Project 4",
                            Type = "Type 4"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 9, 23, 13, 41, 37, 568, DateTimeKind.Local).AddTicks(1408),
                            Name = "Project 5",
                            Type = "Type 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
